#!/usr/bin/env python3
from .lib import *
import sys
import os


def main():
    course_id = sys.argv[1]
    out_dir = sys.argv[2] if len(sys.argv) >= 3 else './out'
    auth_url = sys.argv[3] if len(sys.argv) >= 4 else None

    load_token(auth_url) if auth_url is not None else load_token()

    os.makedirs(out_dir, exist_ok=True)

    for index, clip_id in enumerate(get_course_clip_ids(course_id)):
        print(f'downloading clip {clip_id}')
        download_clip(clip_id, f'{out_dir}/{index+1: 04d}_{clip_id}.mp4')


if __name__ == '__main__':
    main()
